version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.pitest:pitest-maven
    versions:
    - 1.6.2
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: org.junit-pioneer:junit-pioneer
    versions:
    - 1.3.0
    - 1.3.8
  - dependency-name: nl.jqno.equalsverifier:equalsverifier
    versions:
    - 3.5.2
    - 3.5.3
    - 3.5.4
    - 3.5.5
  - dependency-name: net.sf.saxon:Saxon-HE
    versions:
    - "10.3"
  - dependency-name: org.pitest:pitest-junit5-plugin
    versions:
    - "0.12"
  commit-message:
    prefix: dependency
